** EP21 [[https://youtu.be/fzbZbsSEVIE][YouTube]] 

VG : Victor Gaviria

**** VG: Una forma de estar en la ciudad es la exclusión, están en el presente, ¿quién entra?, ¿quién sale?, lugares de mucha alerta, son muy buenos para procesos inmediatos, no son tan buenos para procesos largos, estudiar. 

¿Cuáles procesos inmediatos pueden ser alternativas a delinquir? 

¿Cómo se empatan/operan esos procesos cortos?

Creo que hay que concebir en la lógica joven o adolescente la delincuencia como una debilidad, la debilidad de que el sistema no acepte o entienda mi poder y tener impotencia sobre las injusticias que me circundan y la que se me planta en frente, incluso para aniquilarme.


**** VG: Los pelaos esta buscando alguien que les de un horizonte

**** VG: Hay que hacer entrar las voces de la exclusión 

Además de las redes sociales, ¿a dónde más pueden llevarse esas voces?

**** VG: Los jóvenes de la medellín de ahora, [quienes] están con las últimas palabras.

¿Dónde podemos conocer esas palabras?
- [[https://calvomcarlosm.blogspot.com/2007/03/no-nacimos-pa-semilla.html][Glosario en No Nacimos Pa' Semilla]]
